# Generated by Django 4.1.3 on 2022-12-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('locations', '0001_initial'),
        ('sport_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.rating')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.trainerprofile')),
            ],
            bases=('web_app.rating',),
        ),
        migrations.CreateModel(
            name='GymRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.rating')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.gym')),
            ],
            bases=('web_app.rating',),
        ),
        migrations.CreateModel(
            name='ExerciseRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.rating')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_app.exercise')),
            ],
            bases=('web_app.rating',),
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.rating')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_app.article')),
            ],
            bases=('web_app.rating',),
        ),
    ]
