# Generated by Django 4.1.3 on 2023-01-07 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
