# Generated by Django 4.1.3 on 2022-12-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_gym_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
