# Generated by Django 4.1.3 on 2023-05-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(max_length=30)),
                ('training_field', models.CharField(choices=[('coach', 'Coach'), ('dietitian', 'Dietitian'), ('physiologist', 'Physiologist')], max_length=30)),
                ('years_experience', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('prime_membership', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sports', models.ManyToManyField(to='sport_app.sport')),
            ],
        ),
        migrations.CreateModel(
            name='TraineeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(default='Trainee', max_length=30)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('amateur', 'Amateur'), ('advanced', 'Advanced'), ('professional', 'Professional')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('favourite_exercises', models.ManyToManyField(to='sport_app.exercise')),
                ('favourite_sports', models.ManyToManyField(to='sport_app.sport')),
                ('goals', models.ManyToManyField(to='sport_app.goal')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
