# Generated by Django 4.1.3 on 2022-12-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_trainerprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerprofile',
            options={'permissions': (('sport_app.can_view_article', 'can change article'),)},
        ),
    ]
