# Generated by Django 4.1.3 on 2022-12-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_trainerprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerprofile',
            options={},
        ),
    ]
