# Generated by Django 4.1.3 on 2022-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_trainerprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='prime_membership',
            field=models.BooleanField(default=False),
        ),
    ]
