# Generated by Django 4.1.3 on 2022-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_traineeprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
