# Generated by Django 4.1.3 on 2022-12-15 15:20

from django.db import migrations, models
import project_project.web_app.field_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[project_project.web_app.field_validators.age_validator]),
        ),
    ]
