# Generated by Django 4.1.3 on 2022-12-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='hehe', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
