# Generated by Django 4.1.3 on 2022-12-25 19:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Exercises', 'Exercises'), ('Nutrition', 'Nutrition'), ('Supplements', 'Supplements'), ('Programmes', 'Programmes'), ('Interviews', 'Interviews'), ('Training', 'Training'), ('Science', 'Science'), ('Equipment', 'Equipment and Clothing')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='body_parts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest'), ('Core', 'Core'), ('full_body', 'Full Body')], max_length=50),
        ),
    ]
