# Generated by Django 4.1.3 on 2022-12-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0002_alter_article_category_alter_exercise_body_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
