# Generated by Django 4.1.3 on 2023-01-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0004_goal_date_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
