# Generated by Django 4.1.3 on 2023-01-02 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport_app', '0006_alter_workout_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_app.exercise')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='sport_app.exerciseinstance'),
        ),
    ]
