# Generated by Django 4.1.3 on 2023-01-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0007_exerciseinstance_alter_workout_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sport_app.workout'),
            preserve_default=False,
        ),
    ]
