# Generated by Django 4.1.3 on 2023-01-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0008_remove_exerciseinstance_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinstance',
            name='sets',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
