# Generated by Django 4.1.3 on 2023-01-03 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport_app', '0009_exerciseinstance_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='sport_app.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
