# Generated by Django 4.1.3 on 2023-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0013_rename_readinglistarticle_userreadinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='base_exercise',
            field=models.BooleanField(default=True),
        ),
    ]
