# Generated by Django 4.1.3 on 2023-01-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0014_exercise_base_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
